apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: laravel-in-kubernetes-mysql-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: standard
    tilt.dev/down-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: laravel-in-kubernetes-mysql
spec:
  encryptedData:
    DB_PASSWORD: AgAqjYM9istOVeLW95ea0PSXyjZ7xHExWtNibYCRI2P7t4sJrMtoDeo4lU7RpRCdRq4yWJlSIFwQLejc0xCeMi3NZ6NN+SuJIoE3il9qw0t1xFmuImsorrIgSaCq/9qiBzORC4rLe/jPX3eEHCvi9R6z8I+Ox+OIDCEc76Lm/28W43VY+ZW3ZigBj8D4GLJljAAKRjk8YQv+jKIRxhic/jPaZUG6NAT1Y9cu7og4SEdupKqkgDW8Bikgyu7zrYblDKqaVxXbzU3cIFibvusplryfiI9+OeWczhHNZIiogQsejwPqWurtsU5nd9H4z92/3TBtl8Ys7eJnwgejGAk6EkkUUAnzbP3m1wIRUhd8Q5a3Q4+9DIRf/cndYyBoEtMibpEJzpaw56coe5FiW3CO6bCAjV3AZUAnvofoOnTXxBLeWICs186BFDe5XjmeTZ74y1/ZoGz86G48J1jzbTJ2MKVdLPDCV7G4Jx9xl+cNjQ0H4uCc9skvcGabrv4TNMSFcNdGpPMpfDmExlLt1DnAhGTaEwoIi7nNUAH2Y+cQ3ZbQ44oHgfLPrOUT/N/85jXXBRrE9kTTwr6tDlqTEY62HyzL27KEofKPspg8IgpzbgH0NDJ5+zDhaGgjpUOAeSOMcNo5v4C+V3akoij/AvozGIlXl3UtRSJnrIfAMMv65tb9YOdH4p76uEwhMc2QVJ3oEwNaUEMfhcSxmm+zlg4PJnA7JA==
    DB_USERNAME: AgB9Sq623Wr30d66Pg/82XODHqQD+vJN7bqgmaBjBu7mhFTZaRjsUffa8hxu5BKurnIfjfNo4u5iX5EwhmtNXZHo+pPtrowIzvYMoj/fEa0+Tl35+gGLSVHaZTuhw9zq9l4r2jNw5YS856+OaEuoA0CK/fjXvFE4h9pwhvEdXOBOv8XN1lj0Jc8gE3l872g3i/HJf5vJ7e0exu215/kIDke4GDfJUQa8wB3jlk38FKvslbzoRkYCb693Ju2P3uc7+5NmQzoOu/SPtOXEM6ThT0BChuAyeM5m7R73TzxcOEErgNbFZ+Cmu/cqWpeHL7FJx4b+jkwUeni9qixS4nTILVHi+N+SgdBj3lCq/ztmw0GtHrRnlSXO4ajcLHZCnZ7bEVdcKHmOAavCNi9slVKwpQZwDfqKiv+zWdIgmiGEh+3ye5KdaY7CTWUgScdAE2fZ9VoMv3ocuFhwsgb1rBfT3cvyCbvChvltLmRxtG/8CFPkPOg1SmrFUVXgbXcyVU667vWN5Jso5sQIKEWMWgfzy13BdtdItuQoBSy1ENhn3lmTSErx5QdR0UM8uokNMuufTIGZvsT5NV/alEZPcNvD7FeBRmOnjgUXXJnXsKStIjjGLDIuWT1omUDAVT3j6LXN+nbsbX4Ib4dCFT2Sg+t1vDXLDkYqoR78l3IgmwUfPMFP3gU6CdEo3aB8wVPkzJry4faFi4mPHLsDHXP1zg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: laravel-in-kubernetes-mysql
    type: Opaque

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: laravel-in-kubernetes-mysql
  labels:
    tier: backend
    layer: database
spec:
  selector:
    matchLabels:
      tier: backend
      layer: database
  serviceName: laravel-in-kubernetes-mysql
  replicas: 1
  template:
    metadata:
      labels:
        tier: backend
        layer: database
    spec:
      containers:
        - name: mysql
          image: mysql:8
          ports:
            - name: mysql
              containerPort: 3306
          env:
            - name: MYSQL_RANDOM_ROOT_PASSWORD
              value: "1"
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_DATABASE
              value: laravel-in-kubernetes
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: laravel-in-kubernetes-mysql
                  key: DB_USERNAME
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: laravel-in-kubernetes-mysql
                  key: DB_PASSWORD
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
              # subPath: mysql
          resources:
            requests:
              cpu: 300m
              memory: 256Mi
          livenessProbe:
            exec:
              command:
                - bash
                - -c
                - mysqladmin -u ${MYSQL_USER} -p${MYSQL_PASSWORD} ping
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - bash
                - -c
                - mysql -h 127.0.0.1 -u ${MYSQL_USER} -p${MYSQL_PASSWORD} -e "SELECT 1"
            initialDelaySeconds: 5
            periodSeconds: 2
            timeoutSeconds: 1
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: laravel-in-kubernetes-mysql-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: laravel-in-kubernetes-mysql
spec:
  selector:
    tier: backend
    layer: database
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
