apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{.APP_ID}}"
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: previews
  source:
    path: helm
    repoURL: https://github.com/stickeepaul/kl-argo-test.git
    targetRevision: HEAD
    helm:
      values: |
        APP_ENV: local
        APP_DEBUG: true
        image:
          tag: {{.IMAGE_TAG}}
          pullPolicy: Never
        ingress:
          host: {{.APP_ID}}.previews.com
      version: v3
  destination:
    namespace: "{{.APP_ID}}"
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
