apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-in-kubernetes-fpm
  labels:
    tier: backend
    layer: fpm
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend
      layer: fpm
  template:
    metadata:
      labels:
        app.kubernetes.io/component: fpm
        tier: backend
        layer: fpm
    spec:
      initContainers:
        - name: migrations
          image: "stickeepaul/lik-cli:{{ .Values.image.tag }}"
          command:
            - php
          args:
            - artisan
            - migrate
            - --force
          envFrom:
            - configMapRef:
                name: laravel-in-kubernetes
            - secretRef:
                name: laravel-in-kubernetes
      containers:
        - name: fpm
          image: "stickeepaul/lik-fpm_server:{{ .Values.image.tag }}"
          ports:
            - containerPort: 9000
          envFrom:
            - configMapRef:
                name: laravel-in-kubernetes
            - secretRef:
                name: laravel-in-kubernetes
          volumeMounts:
            - name: code
              mountPath: /opt/apps/laravel-in-kubernetes
      volumes:
        - name: code
          hostPath:
            path: /laravel/
            type: DirectoryOrCreate
          # persistentVolumeClaim:
      #       claimName: 'laravel-in-kubernetes-pvc'
