apiVersion: v1
kind: PersistentVolume
metadata:
  name: laravel-in-kubernetes-volume
  labels:
    type: local
  annotations:
    tilt.dev/down-policy: keep
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "~/pv"
