name: action
on:
  push:
    tags:
      - "v*"
  pull_request:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      # - name: Extract metadata (tags, labels) for DH
      #   id: meta
      #   uses: docker/metadata-action@v4
      #   with:
      #     images: stickeepaul/lik-fpm

      - name: Login to DH
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DH_USER }}
          password: ${{ secrets.DH_PASSWORD }}

      - name: Build and Push
        run: |
          make docker VERSION=pr-${{ github.event.number }}

      - name: Checkout GitOps
        uses: actions/checkout@v3
        with:
          repository: stickeepaul/example-gitops
          token: ${{ secrets.PAT }}
          path: gitops
      - name: Commit to GitOps
        working-directory: gitops
        run: |
          export IMAGE_TAG=pr-${{ github.event.number }}
          export APP_ID=pr-${{ github.event.repository.name }}-${{ github.event.number }}
          curl -sfL -o /usr/local/bin/kyml https://github.com/frigus02/kyml/releases/download/v20210610/kyml_20210610_linux_amd64 && chmod +x /usr/local/bin/kyml
          cat ../kube/preview.yml | kyml tmpl -e APP_ID -e IMAGE_TAG | tee helm/templates/$APP_ID.yaml
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add helm/templates
          git commit -m "Adding PR ${{ github.event.number }} from ${{ github.event.repository.name }}"
          git push
